config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @id = params[:id]
    @book = Book.find(@id)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
  end

  def edit
    @id = params[:id]
    @book = Book.find(@id)
  end

  def destroy
    id = params[:id]
    book = Book.find(id)
    book.destroy
    redirect_to books_path
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @book = Book.find(params[:book_id])

    @review = @book.reviews.build
  end

  def create
    book = Book.find(params[:book_id])
    book.reviews.create(review_params)

    redirect_to book_path(book)


  end

  def review_params
  params.require(:review).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
    <ul>
      <li>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </li>

      <li>
        <%= f.label :author %>
        <%= f.text_field :author %>
      </li>

      <li>
        <%= f.label :price_cents %>
        <%= f.number_field :price_cents %>
      </li>

      <li>
        <%= f.label :quantity %>
        <%= f.number_field :quantity %>
      </li>

      <li>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </li>
    </ul>

    <%= f.submit(class: "button") %>
  <% end %>

app/views/books/index.html.erb
<h1>Welcome to my Super Rad Bookstore!</h1>

<ul>
  <% @books.each do |book|%>
  <li><%=link_to(book.title, book_path(book))%> by <%=book.author%></li>
  <br>
  <% end %>
</ul>


<%= link_to("Add a book", new_book_path, class: "button") %>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>
  <ul>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>

    <li>
      <%= f.label :author %>
      <%= f.text_field :author %>
    </li>

    <li>
      <%= f.label :price_cents %>
      <%= f.number_field :price_cents %>
    </li>

    <li>
      <%= f.label :quantity %>
      <%= f.number_field :quantity %>
    </li>

    <li>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </li>
  </ul>
  <%= f.submit(class: "button") %>
<% end %>

app/views/books/show.html.erb
  <dl>
    <dt>Id</dt>
    <dd><%= @book.id %></dd>

    <dt>Title</dt>
    <dd><%= @book.title %></dd>

    <dt>Author</dt>
    <dd><%= @book.author %></dd>

    <dt>Price</dt>
    <dd><%= number_to_currency(@book.price_cents / 100.0) %></dd>

    <dt>Quantity</dt>
    <dd><%= @book.quantity %></dd>

    <dt>Description</dt>
    <dd><%= @book.description %></dd>
  </dl>

<p> Number of reviews: <%= @book.reviews.count %> </p>
<ul>
  <% @book.reviews.each do |review| %>
    <li> <%= review.body %> </li>
  <% end %>
</ul>

  <%= link_to("Edit book", edit_book_path(@book), class: "button") %>

  <%= link_to("Add a Review", new_book_review_path(@book), class: "button") %>

  <%= button_to("Delete Book", book_path(@book), method: :delete, class: "button danger") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navigation">
  <div class="center">
    <%= link_to "My Super Rad Bookstore", root_path %>
  </div>
</div>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/reviews/new.html.erb
<h1> New review for <%= @book.title %> </h1>

<%= form_for([@book, @review]) do |f| %>
  <ul>
    <li>
      <%= f.label :body %>
      <%= f.text_field :body %>
    </li>
  </ul>

  <%= f.submit(class: "button") %>
<% end %>